# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartGlasses' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMLKit/ImageLabeling'

  # Pods for SmartGlasses

  target 'SmartGlassesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartGlassesUITests' do
    # Pods for testing
  end

end
